### ISSUE TITLE
False detections.

### ISSUE THREAD

**Issue by jensens** [PyCQA/flake8-commas#43]
The plugin states to check ``list`` and ``dict`` - which is fine to me.

But it also detects problems in code like a ``set(api.group.get_roles(group=group, obj=folder, inherit=False))`` is considered a missing traling comma. 
It works with ``set(api.group.get_roles(group=group, obj=folder, inherit=False,))`` - which decreases readability. And does not make any sense to me.

Also a multi line ``def`` like

```
def foo(
    bar,
    baz,
    **kwargs
):
    pass
```

is considered wrong. The plugin wants the wrong syntax (raises SyntaxError on startup):

```
def foo(
    bar,
    baz,
    **kwargs,
):
```

**Comment by graingert** [comment]
Have you tried with 0.5.1? And what's the warning code and message you get?

**Comment by graingert** [comment]
If you need to support versions of python lower than 3.6 you should ignore C816 globally @jensens

**Comment by graingert** [comment]
@jensens this is not a false detection. Your code is only a syntax error because you didn't include "pass":

https://pyfiddle.io/fiddle/f4f2214c-a117-4acc-8bf6-63e7466f2487/?i=true
