### ISSUE TITLE
Is there a way to not require trailing commas on multi-line function calls?

### ISSUE THREAD

**Issue by dbarbar** [PyCQA/flake8-commas#57]
Is it possible to not require trailing commas on multiline function/method calls? At the moment they're getting flagged with C812, which we want for the other multiline errors, just not for function and method calls.

Ideally if the error code for function and method calls was different than C812 we could make our own exceptions for those in our flake8 config.

**Comment by shaleh** [comment]
Are you asking that:
```
data = {
    'a': 1,
    'b': 2  # flagged
}
```

and

```
some_function(
    a,
    b  # not flagged
)
```

**Comment by dbarbar** [comment]
Yes, that's correct.

**Comment by shaleh** [comment]
Why would be helpful I suspect. As I said on another ticket, a reason to use trailing commas is to reduce diff noise in revision control systems. Why is a data structure different from a function call?

**Comment by graingert** [comment]
```python
some_function(
    a,
    b, # there should always be a trailing comma here
)
```

imho this is working as designed
