### ISSUE TITLE
Add test cases for python3.7 and python3.8

### ISSUE THREAD

**Issue by sobolevn** [PyCQA/flake8-commas#60]
Currently both `tox.ini` and [`travis.yml`](https://github.com/PyCQA/flake8-commas/blob/master/travis.yml) do not support latest python versions.

I can send a PR with the fix! 

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by graingert** [comment]
@sobolevn a PR would be great thank you!

**Comment by deluge** [comment]
Hy @sobolevn are there any new information about your PR? ;)

**Comment by sobolevn** [comment]
Nope, I didn't have the time to work on this.
@deluge you can take this over if you wish.

**Comment by deluge** [comment]
@sobolevn Sure!

**Comment by PeterJCLaw** [comment]
I believe this was fixed by https://github.com/PyCQA/flake8-commas/pull/65.
