### ISSUE TITLE
Require commas after splat in Python 3

### ISSUE THREAD

**Issue by PeterJCLaw** [PyCQA/flake8-commas#62]
In at least Python 3.5 and above it's valid to do:
``` python
result = function(
    foo,
    bar,
    *args,
    more,
)
```
This also works for tuple & list literals (and possibly elsewhere).

It would be great if `flake8-commas` could require a comma in such places when one is missing:

``` python
result = function(
    foo,
    bar,
    *args
)
tpl = (
    foo,
    bar,
    *args
)
lst = [
    foo,
    bar,
    *args
]
```

**Comment by graingert** [comment]
For the last 3 cases you should get a C816

**Comment by PeterJCLaw** [comment]
Hrm, we have C816 disabled as we're still on Python 3.5. From what I can tell, these three cases _are_ valid in Python 3.5 though -- could they become C815 instead?

**Comment by PeterJCLaw** [comment]
Turns out: they do get C815s.
Apologies, I think I was just mislead by our config, which had more of flake8-commas' warnings disabled than I'd thought.
I think this is actually working fine.
